import {
  Cpu,
  Mails,
  MemoryStick,
  HdmiPort,
  HardDrive,
  Server,
  MessageCircleMore,
  CalendarDays,
  LayoutDashboardIcon,
  LucideIcon,
  Trash2,
  SquarePen,
  FileSearch,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  ChevronsLeft,
  ChevronsUpDown,
  ArrowUp,
  ArrowDown,
  X,
  ChevronDown,
  Check,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  acervo: Cpu,
  processador: Cpu,
  memoria: MemoryStick,
  placaDeVideo: HdmiPort,
  servidor: Server,
  disco: HardDrive,
  doacoes: Mails,
  eventos: CalendarDays,
  feedbacks: MessageCircleMore,
  delete: Trash2,
  edit: SquarePen,
  details: FileSearch,
  paginaDireita: ChevronRight,
  paginaEsqueda: ChevronLeft,
  primeiraPagina: ChevronsLeft,
  ultimaPagina: ChevronsRight,
  asc: ArrowUp,
  desc: ArrowDown,
  sort: ChevronsUpDown,
  reset: X,
  select: ChevronDown,
  check: Check,
};
